"use strict";
// scales families dictionary
const scaleFamiliesDict = new Map();
// 8 notes
scaleFamiliesDict.set("8bebop_dom", [0, 2, 4, 5, 7, 9, 10, 11]);
scaleFamiliesDict.set("8bebop_maj", [0, 2, 4, 5, 7, 8, 9, 11]);
scaleFamiliesDict.set("8bebop_min_melo", [0, 2, 3, 5, 7, 8, 9, 11]);
scaleFamiliesDict.set("8spanish", [0, 1, 3, 4, 5, 6, 8, 10]);
scaleFamiliesDict.set("8blues_3M7M", [0, 3, 4, 5, 6, 7, 10, 11]);
scaleFamiliesDict.set("8dim", [0, 2, 3, 5, 6, 8, 9, 11]);
// 7 notes
scaleFamiliesDict.set("7major_nat", [0, 2, 4, 5, 7, 9, 11]);
scaleFamiliesDict.set("7minor_harm", [0, 2, 3, 5, 7, 8, 11]);
scaleFamiliesDict.set("7minor_melo", [0, 2, 3, 5, 7, 9, 11]);
scaleFamiliesDict.set("7major_harm", [0, 2, 4, 5, 7, 8, 11]);
scaleFamiliesDict.set("7major_2harm", [0, 1, 4, 5, 7, 8, 11]);
scaleFamiliesDict.set("7major_neap", [0, 1, 3, 5, 7, 9, 11]);
scaleFamiliesDict.set("7minor_neap", [0, 1, 3, 5, 7, 8, 11]);
scaleFamiliesDict.set("7major_hung", [0, 3, 4, 6, 7, 9, 10]);
scaleFamiliesDict.set("7persian", [0, 1, 4, 5, 6, 8, 11]);
scaleFamiliesDict.set("7verdi_enigm", [0, 1, 4, 6, 8, 10, 11]);
scaleFamiliesDict.set("7theta_purvi", [0, 1, 4, 6, 7, 8, 11]);
scaleFamiliesDict.set("7blues_3M", [0, 3, 4, 5, 6, 7, 10]);
scaleFamiliesDict.set("7blues_6M", [0, 3, 5, 6, 7, 9, 10]);
// 6 notes
scaleFamiliesDict.set("6blues", [0, 3, 5, 6, 7, 10]);
scaleFamiliesDict.set("6strange", [0, 2, 4, 6, 8, 10]);
scaleFamiliesDict.set("6major_hexa", [0, 2, 4, 5, 7, 9]);
scaleFamiliesDict.set("6aug", [0, 3, 4, 7, 8, 11]);
scaleFamiliesDict.set("6bb_box", [0, 2, 3, 5, 7, 9]);
scaleFamiliesDict.set("6prom", [0, 2, 4, 6, 9, 10]);
scaleFamiliesDict.set("6prom_nap", [0, 1, 4, 6, 9, 10]);
scaleFamiliesDict.set("6tritone", [0, 1, 4, 6, 7, 10]);
scaleFamiliesDict.set("6tritone_semi", [0, 1, 2, 6, 7, 8]);
scaleFamiliesDict.set("6istrian", [0, 1, 3, 4, 6, 7]);
scaleFamiliesDict.set("6satie", [0, 2, 3, 6, 7, 9]);
// 5 notes
scaleFamiliesDict.set("5major_penta", [0, 2, 4, 7, 9]);
scaleFamiliesDict.set("5javanese", [0, 4, 5, 7, 11]);
scaleFamiliesDict.set("5pelog_bem", [0, 1, 6, 7, 8]);
scaleFamiliesDict.set("5pelog_barang", [0, 2, 6, 7, 9]);
scaleFamiliesDict.set("5jap_in", [0, 1, 5, 7, 8]);
scaleFamiliesDict.set("5jap_insen", [0, 1, 5, 7, 10]);
scaleFamiliesDict.set("5dom_penta", [0, 2, 4, 7, 10]);
scaleFamiliesDict.set("5min_harm_penta", [0, 3, 5, 7, 11]);
scaleFamiliesDict.set("5bartok_penta", [0, 4, 6, 7, 10]);
scaleFamiliesDict.set("5phryg6_penta", [0, 1, 3, 7, 9]);
scaleFamiliesDict.set("5majorb6_penta", [0, 2, 4, 7, 8]);
scaleFamiliesDict.set("5blues_no4_penta", [0, 3, 6, 7, 10]);
scaleFamiliesDict.set("5whole_tone_penta", [0, 4, 6, 8, 10]);
scaleFamiliesDict.set("5kepler", [0, 1, 3, 4, 7]);
// chromatic
scaleFamiliesDict.set("12tet", [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]);
//////////////////////////////////// STRINGS //////////////////////////////////
// international
const scalesDict_int = new Map();
scalesDict_int.set("12tet,1", "Chromatic");
scalesDict_int.set("7notes", "------------------------ 7 NOTES ------------------------");
scalesDict_int.set("7major_nat,1", "Natural major / Ionian");
scalesDict_int.set("7major_nat,6,diff:7major_nat;1", "Natural minor / Aeolian (6th mode)");
scalesDict_int.set("7major_nat,2,diff:7major_nat;6", "Dorian (2nd mode)");
scalesDict_int.set("7major_nat,3,diff:7major_nat;6", "Phrygian (3rd mode)");
scalesDict_int.set("7major_nat,4,diff:7major_nat;1", "Lydian (4th mode)");
scalesDict_int.set("7major_nat,5,diff:7major_nat;1", "Mixolydian (5th mode)");
scalesDict_int.set("7major_nat,7,diff:7major_nat;6", "Locrian (7th mode)");
scalesDict_int.set("7major_nat,sep", "");
scalesDict_int.set("7minor_harm,1,diff:7major_nat;6", "Harmonic minor");
scalesDict_int.set("7minor_harm,2,diff:7major_nat;7", "Locrian ♮6 (2nd mode)");
scalesDict_int.set("7minor_harm,3,diff:7major_nat;1", "Ionian augmented / Ionian #5 (3rd mode)");
scalesDict_int.set("7minor_harm,4,diff:7major_nat;2", "Romanian minor / Ukrainian Dorian (4th mode)");
scalesDict_int.set("7minor_harm,5,diff:7major_nat;3", "Phrygian dominant / Freygish (5th mode)");
scalesDict_int.set("7minor_harm,6,diff:7major_nat;4", "Lydian #2 (6th mode)");
scalesDict_int.set("7minor_harm,7,diff:7major_nat;7", "Ultra Locrian / Altered ♭♭7 (7th mode)");
scalesDict_int.set("7minor_harm,sep", "");
scalesDict_int.set("7minor_melo,1,diff:7major_nat;6", "Melodic minor");
scalesDict_int.set("7minor_melo,2,diff:7major_nat;6", "Dorian ♭2 / Phrygian ♮6 (2nd mode)");
scalesDict_int.set("7minor_melo,3,diff:7major_nat;4", "Lydian augmented / Lydian #5 (3rd mode)");
scalesDict_int.set("7minor_melo,4,diff:7major_nat;4", "Bartok / Lydian Dominant (4th mode)");
scalesDict_int.set("7minor_melo,5,diff:7major_nat;5", "Hindu / Mixolydian ♭6 (5th mode)");
scalesDict_int.set("7minor_melo,6,diff:7major_nat;7", "Half-diminished / Locrian ♮2 (6th mode)");
scalesDict_int.set("7minor_melo,7,diff:7major_nat;7", "Super Locrian / Altered (7th mode)");
scalesDict_int.set("7minor_melo,sep", "");
scalesDict_int.set("7major_2harm,1,diff:7major_nat;1", "Double harm. major / Byzantine / Gypsy");
scalesDict_int.set("7major_2harm,2,diff:7major_nat;4", "Lydian #2 #6 (2nd mode)");
scalesDict_int.set("7major_2harm,3,diff:7major_nat;3", "Ultra phrygian (3rd mode)");
scalesDict_int.set("7major_2harm,4,diff:7major_nat;6", "Hungarian minor (4th mode)");
scalesDict_int.set("7major_2harm,5", "Oriental / Asian (5th mode)");
scalesDict_int.set("7major_2harm,6,diff:7major_nat;1", "Ionian augmented #2 (6th mode)");
scalesDict_int.set("7major_2harm,7,diff:7major_nat;7", "Locrian ♭♭3 ♭♭7 (7th mode)");
scalesDict_int.set("7major_2harm,sep", "");
scalesDict_int.set("7major_harm,1,diff:7major_nat;1", "Harmonic major / Ionian ♭6");
scalesDict_int.set("7major_harm,2,diff:7major_nat;2", "Nahawand Murassa' / Dorian ♭5 (2nd mode)");
scalesDict_int.set("7major_harm,3,diff:7major_nat;3", "Phrygian ♭4 (3rd mode)");
scalesDict_int.set("7major_harm,4,diff:7major_nat;4", "Lydian ♭3 / Melodic minor #4 (4th mode)");
scalesDict_int.set("7major_harm,5,diff:7major_nat;5", "Zanjaran / Mixolydian ♭2 (5th mode)");
scalesDict_int.set("7major_harm,6,diff:7major_nat;4", "Lydian augmented #2 (6th mode)");
scalesDict_int.set("7major_harm,7,diff:7major_nat;7", "Locrian ♭♭7 (7th mode)");
scalesDict_int.set("7major_neap,1,diff:7minor_melo;1", "Neapolitan major");
scalesDict_int.set("7major_neap,2", "Leading whole tone (2nd mode)");
scalesDict_int.set("7major_neap,4,diff:7major_nat;4", "Lydian minor (4th mode)");
scalesDict_int.set("7major_neap,5,diff:7major_nat;7", "Arabian / Locrian major (5th mode)");
scalesDict_int.set("7major_neap,sep", "");
scalesDict_int.set("7minor_neap,1,diff:7major_nat;6", "Neapolitan minor");
scalesDict_int.set("7minor_neap,2,diff:7major_nat;4", "Lydian #6 (2nd mode)");
scalesDict_int.set("7minor_neap,4", "Hungarian gypsy (4th mode)");
scalesDict_int.set("7minor_neap,sep", "");
scalesDict_int.set("7persian,1,diff:7major_2harm;1", "Persian");
scalesDict_int.set("7persian,4", "Todi theta (4th mode)");
scalesDict_int.set("7persian,sep", "");
scalesDict_int.set("7major_hung,1", "Hungarian major");
scalesDict_int.set("7verdi_enigm,1", "Verdi's Enigmatica");
scalesDict_int.set("7theta_purvi,1,diff:7major_2harm;1", "Purvi theta / Kamavardhani");
scalesDict_int.set("7others,sep", "");
scalesDict_int.set("7blues_3M,1,diff:5major_penta;5", "Blues (+ 3M)");
scalesDict_int.set("7blues_6M,1,diff:5major_penta;5", "Blues (+ 6M)");
scalesDict_int.set("7theta_purvi,2,diff:5major_penta;5", "Blues (+ 7M)");
scalesDict_int.set("7others_blues,sep", "");
scalesDict_int.set("8notes", "------------------------ 8 NOTES ------------------------");
scalesDict_int.set("8bebop_dom,1,diff:7major_nat;1", "Bebop dominant");
scalesDict_int.set("8bebop_dom,2,diff:7major_nat;6", "Natural minor + Dorian (2nd mode)");
scalesDict_int.set("8bebop_dom,4", "Ichikosucho (4th mode)");
scalesDict_int.set("8bebop_dom,5,diff:7major_nat;2", "Bebop Dorian / Bebop minor (5th mode)");
scalesDict_int.set("8bebop_dom,sep", "");
scalesDict_int.set("8bebop_maj,1,diff:7major_nat;1", "Bebop major");
scalesDict_int.set("8bebop_maj,2,diff:7major_nat;6", "Dorian + Blue note (2nd mode)");
scalesDict_int.set("8bebop_maj,7,diff:7minor_harm;1", "Bebop harmonic minor (7th mode)");
scalesDict_int.set("8bebop_maj,sep", "");
scalesDict_int.set("8bebop_min_melo,1,diff:7minor_melo;1", "Bebop melodic minor");
scalesDict_int.set("8bebop_min_melo,sep", "");
scalesDict_int.set("8spanish,1", "Spanish");
scalesDict_int.set("8blues_3M7M,1,diff:5major_penta;5", "Blues (+ 3M, 7M)");
scalesDict_int.set("8spanish,sep", "");
scalesDict_int.set("8dim,1", "Diminished");
scalesDict_int.set("8dim,2", "Dominant diminished / Dom-dim (2nd mode)");
scalesDict_int.set("8others,sep", "");
scalesDict_int.set("6notes", "------------------------ 6 NOTES ------------------------");
scalesDict_int.set("6blues,1,diff:5major_penta;5", "Blues / Penta. minor + Blue note");
scalesDict_int.set("6strange,1", "Whole tone / Strange / Debussy");
scalesDict_int.set("6main,sep", "");
scalesDict_int.set("6aug,1", "Augmented / Irish / Scottish");
scalesDict_int.set("6aug,2", "Six-tone symmetrical (2nd mode)");
scalesDict_int.set("6aug,sep", "");
scalesDict_int.set("6prom,1", "Prometheus / Mystic");
scalesDict_int.set("6prom,4", "Mystic tritone (4th mode)");
scalesDict_int.set("6prom,sep", "");
scalesDict_int.set("6bb_box,1", "B.B. Box");
scalesDict_int.set("6major_hexa,1", "Hexatonic major");
scalesDict_int.set("6prom_nap,1", "Prometheus neapolitan");
scalesDict_int.set("6tritone,1", "Tritone / Petrushka");
scalesDict_int.set("6tritone_semi,1", "Two-semitone tritone");
scalesDict_int.set("6istrian,1", "Istrian");
scalesDict_int.set("6satie,1", "Satie");
scalesDict_int.set("6others,sep", "");
scalesDict_int.set("5notes", "------------------------ 5 NOTES ------------------------");
scalesDict_int.set("5major_penta,1", "Major pentatonic / Mongolian");
scalesDict_int.set("5major_penta,5", "Minor Pentatonic (5th mode)");
scalesDict_int.set("5major_penta,2", "Egyptian / Suspended (2nd mode)");
scalesDict_int.set("5major_penta,3", "Blues minor / Man gong (3rd mode)");
scalesDict_int.set("5major_penta,4", "Blues major / Yo / Ritsusen (4th mode)");
scalesDict_int.set("5major_penta,sep", "");
scalesDict_int.set("5jap_in,1", "In / Miyako-Bushi");
scalesDict_int.set("5jap_in,2", "Chinese / Lydian pentatonic (2nd mode)");
scalesDict_int.set("5jap_in,3", "Hirajoshi / Tezeta (3rd mode)");
scalesDict_int.set("5jap_in,4", "Iwato (4th mode)");
scalesDict_int.set("5jap_in,sep", "");
scalesDict_int.set("5jap_insen,1", "Insen");
scalesDict_int.set("5jap_insen,4,diff:5major_penta;5", "Minor Pentatonic ♭5 (4th mode)");
scalesDict_int.set("5jap_insen,5", "Kumoi (5th mode)");
scalesDict_int.set("5jap_insen,sep", "");
scalesDict_int.set("5javanese,1", "Javanese / Ryu Kyu");
scalesDict_int.set("5javanese,2", "Balinese (2nd mode)");
scalesDict_int.set("5javanese,5", "Iwato bis (5th mode)");
scalesDict_int.set("5javanese_sep", "");
scalesDict_int.set("5pelog_barang,1", "Pelog Barang");
scalesDict_int.set("5pelog_barang,2", "Hindu / Mixolydian Pentatonic (2nd mode)");
scalesDict_int.set("5pelog_barang_sep", "");
scalesDict_int.set("5pelog_bem,1", "Pelog Bem");
scalesDict_int.set("5pelog_bem_sep", "");
scalesDict_int.set("5dom_penta,1,diff:5major_penta;1", "Dominant Pentatonic");
scalesDict_int.set("5dom_penta,4,diff:5major_penta;5", "Dorian Pentatonic (4th mode)");
scalesDict_int.set("5dom_penta_sep", "");
scalesDict_int.set("5bartok_penta,1,diff:5major_penta;5", "Bartok Pentatonic");
scalesDict_int.set("5bartok_penta,4,diff:5major_penta;5", "Minor Melodic Pentatonic (4th mode)");
scalesDict_int.set("5bartok_penta_sep", "");
scalesDict_int.set("5min_harm_penta,1,diff:5major_penta;5", "Minor Harmonic Pentatonic");
scalesDict_int.set("5min_harm_penta,4", "Myxolydian ♭6 Pentatonic (4th mode)");
scalesDict_int.set("5min_harm_penta_sep", "");
scalesDict_int.set("5phryg6_penta,1,diff:5major_penta;1", "Phrygian Pentatonic ♮6");
scalesDict_int.set("5majorb6_penta,1,diff:5major_penta;1", "Major Pentatonic ♭6");
scalesDict_int.set("5whole_tone_penta,1", "Whole Tone Pentatonic");
scalesDict_int.set("5blues_no4_penta,1,diff:5major_penta;5", "Blues no4");
scalesDict_int.set("5kepler,1", "Kepler");
scalesDict_int.set("5others,sep", "");
/////////////////////////////////// FRENCH ////////////////////////////////////
const scalesDict_fr = new Map();
scalesDict_fr.set("12tet,1", "Chromatique");
scalesDict_fr.set("7major_nat,1", "Majeur naturel / Ionien");
scalesDict_fr.set("7major_nat,6,diff:7major_nat;1", "Mineur naturel / Eolien (6e mode)");
scalesDict_fr.set("7major_nat,2,diff:7major_nat;6", "Dorien (2e mode)");
scalesDict_fr.set("7major_nat,3,diff:7major_nat;6", "Phrygien (3e mode)");
scalesDict_fr.set("7major_nat,4,diff:7major_nat;1", "Lydien (4e mode)");
scalesDict_fr.set("7major_nat,5,diff:7major_nat;1", "Mixolydien (5e mode)");
scalesDict_fr.set("7major_nat,7,diff:7major_nat;6", "Locrien (7e mode)");
scalesDict_fr.set("7minor_harm,1,diff:7major_nat;6", "Mineur harmonique");
scalesDict_fr.set("7minor_harm,2,diff:7major_nat;7", "Locrien ♮6 (2e mode)");
scalesDict_fr.set("7minor_harm,3,diff:7major_nat;1", "Ionien augmenté / Ionien #5 (3e mode)");
scalesDict_fr.set("7minor_harm,4,diff:7major_nat;2", "Roumain mineur / Dorien Ukrainien (4e mode)");
scalesDict_fr.set("7minor_harm,5,diff:7major_nat;3", "Phrygien dominant / Phrygien majeur (5e mode)");
scalesDict_fr.set("7minor_harm,6,diff:7major_nat;4", "Lydien #2 (6e mode)");
scalesDict_fr.set("7minor_harm,7,diff:7major_nat;7", "Ultra Locrien / Altérée ♭♭7 (7e mode)");
scalesDict_fr.set("7minor_melo,1,diff:7major_nat;6", "Mineur mélodique");
scalesDict_fr.set("7minor_melo,2,diff:7major_nat;6", "Dorien ♭2 / Phrygien ♮6 (2e mode)");
scalesDict_fr.set("7minor_melo,3,diff:7major_nat;4", "Lydien augmenté / Lydien #5 (3e mode)");
scalesDict_fr.set("7minor_melo,4,diff:7major_nat;4", "Bartok / Lydien Dominant (4e mode)");
scalesDict_fr.set("7minor_melo,5,diff:7major_nat;5", "Hindou / Mixolydien ♭6 (5e mode)");
scalesDict_fr.set("7minor_melo,6,diff:7major_nat;7", "Semi-diminué / Locrien ♮2 (6e mode)");
scalesDict_fr.set("7minor_melo,7,diff:7major_nat;7", "Super Locrien / Altérée (7e mode)");
scalesDict_fr.set("7major_2harm,1,diff:7major_nat;1", "Double majeur harm. / Byzantin / Gitan");
scalesDict_fr.set("7major_2harm,2,diff:7major_nat;4", "Lydien #2 #6 (2e mode)");
scalesDict_fr.set("7major_2harm,3,diff:7major_nat;3", "Ultra phrygien (3e mode)");
scalesDict_fr.set("7major_2harm,4,diff:7major_nat;6", "Hongrois mineur (4e mode)");
scalesDict_fr.set("7major_2harm,5", "Oriental / Asiatique (5e mode)");
scalesDict_fr.set("7major_2harm,6,diff:7major_nat;1", "Ionien augmenté #2 (6e mode)");
scalesDict_fr.set("7major_2harm,7,diff:7major_nat;7", "Locrien ♭♭3 ♭♭7 (7e mode)");
scalesDict_fr.set("7major_harm,1,diff:7major_nat;1", "Majeur harmonique / Ionien ♭6");
scalesDict_fr.set("7major_harm,2,diff:7major_nat;2", "Nahawand Murassa' / Dorien ♭5 (2e mode)");
scalesDict_fr.set("7major_harm,3,diff:7major_nat;3", "Phrygien ♭4 (3e mode)");
scalesDict_fr.set("7major_harm,4,diff:7major_nat;4", "Lydien ♭3 / Mineure mélodique #4 (4e mode)");
scalesDict_fr.set("7major_harm,5,diff:7major_nat;5", "Zanjaran / Mixolydien ♭2 (5e mode)");
scalesDict_fr.set("7major_harm,6,diff:7major_nat;4", "Lydien augmenté #2 (6e mode)");
scalesDict_fr.set("7major_harm,7,diff:7major_nat;7", "Locrien ♭♭7 (7e mode)");
scalesDict_fr.set("7major_neap,1,diff:7minor_melo;1", "Napolitain majeur");
scalesDict_fr.set("7major_neap,2", "Tons en tête (2e mode)");
scalesDict_fr.set("7major_neap,4,diff:7major_nat;4", "Lydien mineur (4e mode)");
scalesDict_fr.set("7major_neap,5,diff:7major_nat;7", "Arabe / Locrien majeur (5e mode)");
scalesDict_fr.set("7minor_neap,1,diff:7major_nat;6", "Napolitain mineur");
scalesDict_fr.set("7minor_neap,2,diff:7major_nat;4", "Lydien #6 (2e mode)");
scalesDict_fr.set("7minor_neap,4", "Hongrois gitan (4e mode)");
scalesDict_fr.set("7persian,1,diff:7major_2harm;1", "Persan");
scalesDict_fr.set("7persian,4", "Todi theta (4e mode)");
scalesDict_fr.set("7major_hung,1", "Hongrois majeur");
scalesDict_fr.set("7verdi_enigm,1", "Enigmatique de Verdi");
scalesDict_fr.set("8bebop_dom,1,diff:7major_nat;1", "Bebop dominant");
scalesDict_fr.set("8bebop_dom,2,diff:7major_nat;6", "Mineure naturelle + Dorien (2e mode)");
scalesDict_fr.set("8bebop_dom,5,diff:7major_nat;2", "Bebop dorien / Bebop mineur (5e mode)");
scalesDict_fr.set("8bebop_maj,1,diff:7major_nat;1", "Bebop majeur");
scalesDict_fr.set("8bebop_maj,2,diff:7major_nat;6", "Dorien + Blue note (2e mode)");
scalesDict_fr.set("8bebop_maj,7,diff:7minor_harm;1", "Bebop mineur harmonique (7e mode)");
scalesDict_fr.set("8bebop_min_melo,1,diff:7minor_melo;1", "Bebop mineur mélodique");
scalesDict_fr.set("8spanish,1", "Espagnole");
scalesDict_fr.set("8dim,1", "Diminué");
scalesDict_fr.set("8dim,2", "Dominant diminué / Dom-dim (2e mode)");
scalesDict_fr.set("6blues,1,diff:5major_penta;5", "Blues / Penta. mineur + Blue note");
scalesDict_fr.set("6strange,1", "Tons / Etrange / Debussy");
scalesDict_fr.set("6aug,1", "Augmenté / Irlandais / Ecossais");
scalesDict_fr.set("6aug,2", "6 tons symétrique (2e mode)");
scalesDict_fr.set("6prom,1", "Prométhée / Mystique");
scalesDict_fr.set("6prom,4", "Mystique triton (4e mode)");
scalesDict_fr.set("6major_hexa,1", "Hexatonique majeur");
scalesDict_fr.set("6prom_nap,1", "Prométhée napolitain");
scalesDict_fr.set("6tritone,1", "Triton / Petrouchka");
scalesDict_fr.set("6tritone_semi,1", "2 semi-tons triton");
scalesDict_fr.set("6istrian,1", "Istrien");
scalesDict_fr.set("5major_penta,1", "Pentatonique majeur / Mongolien");
scalesDict_fr.set("5major_penta,5", "Pentatonique mineur (5e mode)");
scalesDict_fr.set("5major_penta,2", "Egyptien / Suspendu (2e mode)");
scalesDict_fr.set("5major_penta,3", "Blues mineur / Man gong (3e mode)");
scalesDict_fr.set("5major_penta,4", "Blues majeur / Yo / Ritsusen (4e mode)");
scalesDict_fr.set("5jap_in,1", "In / Miyako-Bushi");
scalesDict_fr.set("5jap_in,2", "Chinois / Pentatonique lydienne (2e mode)");
scalesDict_fr.set("5jap_in,3", "Hirajoshi / Tezeta (3e mode)");
scalesDict_fr.set("5jap_in,4", "Iwato (4e mode)");
scalesDict_fr.set("5jap_insen,1", "Insen");
scalesDict_fr.set("5jap_insen,4,diff:5major_penta;5", "Pentatonique mineure ♭5 (4e mode)");
scalesDict_fr.set("5jap_insen,5", "Kumoi (5e mode)");
scalesDict_fr.set("5javanese,1", "Javanais / Ryu Kyu");
scalesDict_fr.set("5javanese,2", "Balinais (2e mode)");
scalesDict_fr.set("5javanese,5", "Iwato bis (5e mode)");
scalesDict_fr.set("5pelog_barang,2", "Pentatonique mixolydienne / Hindou (2e mode)");
scalesDict_fr.set("5dom_penta,1,diff:5major_penta;1", "Pentatonique dominante");
scalesDict_fr.set("5dom_penta,4,diff:5major_penta;5", "Pentatonique dorienne (4e mode)");
scalesDict_fr.set("5bartok_penta,1,diff:5major_penta;5", "Pentatonique Bartok");
scalesDict_fr.set("5bartok_penta,4,diff:5major_penta;5", "Pentatonique mineure mélodique (4e mode)");
scalesDict_fr.set("5min_harm_penta,1,diff:5major_penta;5", "Pentatonique mineure harmonique");
scalesDict_fr.set("5min_harm_penta,4", "Pentatonique mixolydienne ♭6 (4e mode)");
scalesDict_fr.set("5majorb6_penta,1,diff:5major_penta;1", "Pentatonique majeure ♭6");
scalesDict_fr.set("5phryg6_penta,1,diff:5major_penta;1", "Pentatonique phrygien ♮6");
scalesDict_fr.set("5whole_tone_penta,1", "Pentatonique tonique 6 tons");
/////////////////////////////////// SPANISH ////////////////////////////////////
const scalesDict_es = new Map();
scalesDict_es.set("12tet,1", "Cromática");
scalesDict_es.set("7major_nat,1", "Mayor natural / Jónico");
scalesDict_es.set("7major_nat,6,diff:7major_nat;1", "Menor natural / Eólico (6º modo)");
scalesDict_es.set("7major_nat,2,diff:7major_nat;6", "Dórico (2º modo)");
scalesDict_es.set("7major_nat,3,diff:7major_nat;6", "Frigio (3º modo)");
scalesDict_es.set("7major_nat,4,diff:7major_nat;1", "Lidio (4º modo)");
scalesDict_es.set("7major_nat,5,diff:7major_nat;1", "Mixolydio (5º modo)");
scalesDict_es.set("7major_nat,7,diff:7major_nat;6", "Locrio (7º modo)");
scalesDict_es.set("7minor_harm,1,diff:7major_nat;6", "Menor armónica");
scalesDict_es.set("7minor_harm,2,diff:7major_nat;7", "Locrio ♮6 (2º modo)");
scalesDict_es.set("7minor_harm,3,diff:7major_nat;1", "Jónico aumentado / Jónico #5 (3º modo)");
scalesDict_es.set("7minor_harm,4,diff:7major_nat;2", "Menor rumano / Dórico ucraniano (4º modo)");
scalesDict_es.set("7minor_harm,5,diff:7major_nat;3", "Frigio dominante / Frigio mayor (5º modo)");
scalesDict_es.set("7minor_harm,6,diff:7major_nat;4", "Lidio #2 (6º modo)");
scalesDict_es.set("7minor_harm,7,diff:7major_nat;7", "Ultra Locrio / Alterada ♭♭7 (7º modo)");
scalesDict_es.set("7minor_melo,1,diff:7major_nat;6", "Menor melódica");
scalesDict_es.set("7minor_melo,2,diff:7major_nat;6", "Dórico ♭2 / Frigio ♮6 (2º modo)");
scalesDict_es.set("7minor_melo,3,diff:7major_nat;4", "Lidio aumentado / Lidio #5 (3º modo)");
scalesDict_es.set("7minor_melo,4,diff:7major_nat;4", "Bartok / Lidio dominante (4º modo)");
scalesDict_es.set("7minor_melo,5,diff:7major_nat;5", "Hindú / Mixolidio ♭6 (5º modo)");
scalesDict_es.set("7minor_melo,6,diff:7major_nat;7", "Semidisminuido / Locrio ♮2 (6º modo)");
scalesDict_es.set("7minor_melo,7,diff:7major_nat;7", "Super Locrio / Alterada (7º modo)");
scalesDict_es.set("7major_2harm,1,diff:7major_nat;1", "Doble mayor armónica / Bizantino / Gitano");
scalesDict_es.set("7major_2harm,2,diff:7major_nat;4", "Lidio #2 #6 (2º modo)");
scalesDict_es.set("7major_2harm,3,diff:7major_nat;3", "Ultra frigio (3º modo)");
scalesDict_es.set("7major_2harm,4,diff:7major_nat;6", "Menor húngaro (4º modo)");
scalesDict_es.set("7major_2harm,5", "Oriental / Asiático (5º modo)");
scalesDict_es.set("7major_2harm,6,diff:7major_nat;1", "Jónico aumentado #2 (6º modo)");
scalesDict_es.set("7major_2harm,7,diff:7major_nat;7", "Locrio ♭♭3 ♭♭7 (7º modo)");
scalesDict_es.set("7major_harm,1,diff:7major_nat;1", "Mayor armónica / Jónico ♭6");
scalesDict_es.set("7major_harm,2,diff:7major_nat;2", "Nahawand Murassa' / Dórico ♭5 (2º modo)");
scalesDict_es.set("7major_harm,3,diff:7major_nat;3", "Frigio ♭4 (3º modo)");
scalesDict_es.set("7major_harm,4,diff:7major_nat;4", "Lidio ♭3 / Menor melódica #4 (4º modo)");
scalesDict_es.set("7major_harm,5,diff:7major_nat;5", "Zanjaran / Mixolidio ♭2 (5º modo)");
scalesDict_es.set("7major_harm,6,diff:7major_nat;4", "Lidio aumentado #2 (6º modo)");
scalesDict_es.set("7major_harm,7,diff:7major_nat;7", "Locrio ♭♭7 (7º modo)");
scalesDict_es.set("7major_neap,1,diff:7minor_melo;1", "Napolitano mayor");
scalesDict_es.set("7major_neap,2", "Tonos en cabeza (2º modo)");
scalesDict_es.set("7major_neap,4,diff:7major_nat;4", "Lidio menor (4º modo)");
scalesDict_es.set("7major_neap,5,diff:7major_nat;7", "Árabe / Locrio mayor (5º modo)");
scalesDict_es.set("7minor_neap,1,diff:7major_nat;6", "Napolitano menor");
scalesDict_es.set("7minor_neap,2,diff:7major_nat;4", "Lidio #6 (2º modo)");
scalesDict_es.set("7minor_neap,4", "Gitano húngaro (4º modo)");
scalesDict_es.set("7persian,1,diff:7major_2harm;1", "Persa");
scalesDict_es.set("7persian,4", "Todi theta (4º modo)");
scalesDict_es.set("7major_hung,1", "Mayor húngaro");
scalesDict_es.set("7verdi_enigm,1", "Enigmática de Verdi");
scalesDict_es.set("8bebop_dom,1,diff:7major_nat;1", "Bebop dominante");
scalesDict_es.set("8bebop_dom,2,diff:7major_nat;6", "Menor natural + Dórico (2º modo)");
scalesDict_es.set("8bebop_dom,5,diff:7major_nat;2", "Bebop dórico / Bebop menor (5º modo)");
scalesDict_es.set("8bebop_maj,1,diff:7major_nat;1", "Bebop majeur");
scalesDict_es.set("8bebop_maj,2,diff:7major_nat;6", "Dórico + Blue note (2º modo)");
scalesDict_es.set("8bebop_maj,7,diff:7minor_harm;1", "Bebop menor armónico (7º modo)");
scalesDict_es.set("8bebop_min_melo,1,diff:7minor_melo;1", "Bebop menor melódico");
scalesDict_es.set("8spanish,1", "Española");
scalesDict_es.set("8dim,1", "Disminuida");
scalesDict_es.set("8dim,2", "Dominante disminuida / Dom-dis (2º modo)");
scalesDict_es.set("6blues,1,diff:5major_penta;5", "Blues / Penta. menor + Blue note");
scalesDict_es.set("6strange,1", "Tonos / Extraño / Debussy");
scalesDict_es.set("6aug,1", "Aumentada / Irlandesa / Escocesa");
scalesDict_es.set("6aug,2", "6 tonos simétricos (2º modo)");
scalesDict_es.set("6prom,1", "Prometeo / Místico");
scalesDict_es.set("6prom,4", "Místico tritono (4º modo)");
scalesDict_es.set("6major_hexa,1", "Hexatónica mayor");
scalesDict_es.set("6prom_nap,1", "Prometeo napolitano");
scalesDict_es.set("6tritone,1", "Triton / Petrouchka");
scalesDict_es.set("6tritone_semi,1", "2 semitonos tritono");
scalesDict_es.set("6istrian,1", "Istrio");
scalesDict_es.set("5major_penta,1", "Pentatónica mayor / Mongol");
scalesDict_es.set("5major_penta,5", "Pentatónica menor (5º modo)");
scalesDict_es.set("5major_penta,2", "Egipcia / Suspendida (2º modo)");
scalesDict_es.set("5major_penta,3", "Blues menor / Man gong (3º modo)");
scalesDict_es.set("5major_penta,4", "Blues mayor / Yo / Ritsusen (4º modo)");
scalesDict_es.set("5jap_in,1", "In / Miyako-Bushi");
scalesDict_es.set("5jap_in,2", "Chino / Pentatónica lidia (2º modo)");
scalesDict_es.set("5jap_in,3", "Hirajoshi / Tezeta (3º modo)");
scalesDict_es.set("5jap_in,4", "Iwato (4º modo)");
scalesDict_es.set("5jap_insen,1", "Insen");
scalesDict_es.set("5jap_insen,4,diff:5major_penta;5", "Pentatónica menor ♭5 (4º modo)");
scalesDict_es.set("5jap_insen,5", "Kumoi (5º modo)");
scalesDict_es.set("5javanese,1", "Javanés / Ryu Kyu");
scalesDict_es.set("5javanese,2", "Balinesa (2º modo)");
scalesDict_es.set("5javanese,5", "Iwato bis (5º modo)");
scalesDict_es.set("5pelog_barang,2", "Pentatónica Mixolidia / Hindú (2º modo)");
scalesDict_es.set("5dom_penta,1,diff:5major_penta;1", "Pentatónica dominante");
scalesDict_es.set("5dom_penta,4,diff:5major_penta;5", "Pentatónica dórica (4º modo)");
scalesDict_es.set("5bartok_penta,1,diff:5major_penta;5", "Pentatónica Bartok");
scalesDict_es.set("5bartok_penta,4,diff:5major_penta;5", "Pentatónica menor melódica (4º modo)");
scalesDict_es.set("5min_harm_penta,1,diff:5major_penta;5", "Pentatónica menor armónica");
scalesDict_es.set("5min_harm_penta,4", "Pentatónica mixolidiana ♭6 (4º modo)");
scalesDict_es.set("5majorb6_penta,1,diff:5major_penta;1", "Pentatónica mayor ♭6");
scalesDict_es.set("5phryg6_penta,1,diff:5major_penta;1", "Pentatónica frigia ♮6");
scalesDict_es.set("5whole_tone_penta,1", "Pentatónica 6 tonos");
scalesDict_es.set("5blues_no4_penta,1,diff:5major_penta;5", "Blues no4");
scalesDict_es.set("5kepler,1", "Kepler");
scalesDict_es.set("5others,sep", "");
/////////////////////////////////// ITALIAN ////////////////////////////////////
const scalesDict_it = new Map();
scalesDict_it.set("12tet,1", "Cromatico");
scalesDict_it.set("7major_nat,1", "Maggiore naturale / Ionico");
scalesDict_it.set("7major_nat,6,diff:7major_nat;1", "Minore naturale / Eolio (6º modo)");
scalesDict_it.set("7major_nat,2,diff:7major_nat;6", "Dorico (2º modo)");
scalesDict_it.set("7major_nat,3,diff:7major_nat;6", "Frigio (3º modo)");
scalesDict_it.set("7major_nat,4,diff:7major_nat;1", "Lidio (4º modo)");
scalesDict_it.set("7major_nat,5,diff:7major_nat;1", "Misolidio (5º modo)");
scalesDict_it.set("7major_nat,7,diff:7major_nat;6", "Locrio (7º modo)");
scalesDict_it.set("7minor_harm,1,diff:7major_nat;6", "Minore armonica");
scalesDict_it.set("7minor_harm,2,diff:7major_nat;7", "Locrio ♮6 (2º modo)");
scalesDict_it.set("7minor_harm,3,diff:7major_nat;1", "Ionico aumentato / Ionico #5 (3º modo)");
scalesDict_it.set("7minor_harm,4,diff:7major_nat;2", "Minore rumeno / Dorico ucraino (4º modo)");
scalesDict_it.set("7minor_harm,5,diff:7major_nat;3", "Frigio dominante / Frigio maggiore (5º modo)");
scalesDict_it.set("7minor_harm,6,diff:7major_nat;4", "Lidio #2 (6º modo)");
scalesDict_it.set("7minor_harm,7,diff:7major_nat;7", "Ultra locrio / Alterata ♭♭7 (7º modo)");
scalesDict_it.set("7minor_melo,1,diff:7major_nat;6", "Minore melodica");
scalesDict_it.set("7minor_melo,2,diff:7major_nat;6", "Dorico ♭2 / Frigio ♮6 (2º modo)");
scalesDict_it.set("7minor_melo,3,diff:7major_nat;4", "Lidio aumentato / Lidio #5 (3º modo)");
scalesDict_it.set("7minor_melo,4,diff:7major_nat;4", "Bartok / Lidio dominante (4º modo)");
scalesDict_it.set("7minor_melo,5,diff:7major_nat;5", "Indiano / Misolidio ♭6 (5º modo)");
scalesDict_it.set("7minor_melo,6,diff:7major_nat;7", "Semidiminuito / Locrio ♮2 (6º modo)");
scalesDict_it.set("7minor_melo,7,diff:7major_nat;7", "Super locrio / Alterata (7º modo)");
scalesDict_it.set("7major_2harm,1,diff:7major_nat;1", "Doppio maggiore armonico / Bizantino / Zingaro");
scalesDict_it.set("7major_2harm,2,diff:7major_nat;4", "Lidio #2 #6 (2º modo)");
scalesDict_it.set("7major_2harm,3,diff:7major_nat;3", "Ultra frigio (3º modo)");
scalesDict_it.set("7major_2harm,4,diff:7major_nat;6", "Minore ungherese (4º modo)");
scalesDict_it.set("7major_2harm,5", "Orientale / Asiatico (5º modo)");
scalesDict_it.set("7major_2harm,6,diff:7major_nat;1", "Ionico aumentato #2 (6º modo)");
scalesDict_it.set("7major_2harm,7,diff:7major_nat;7", "Locrio ♭♭3 ♭♭7 (7º modo)");
scalesDict_it.set("7major_harm,1,diff:7major_nat;1", "Maggiore armonico / Ionico ♭6");
scalesDict_it.set("7major_harm,2,diff:7major_nat;2", "Nahawand Murassa' / Dorico ♭5 (2º modo)");
scalesDict_it.set("7major_harm,3,diff:7major_nat;3", "Frigio ♭4 (3º modo)");
scalesDict_it.set("7major_harm,4,diff:7major_nat;4", "Lidio ♭3 / Minore melodica #4 (4º modo)");
scalesDict_it.set("7major_harm,5,diff:7major_nat;5", "Zanjaran / Misolidio ♭2 (5º modo)");
scalesDict_it.set("7major_harm,6,diff:7major_nat;4", "Lidio aumentato #2 (6º modo)");
scalesDict_it.set("7major_harm,7,diff:7major_nat;7", "Locrio ♭♭7 (7º modo)");
scalesDict_it.set("7major_neap,1,diff:7minor_melo;1", "Napolitano maggiore");
scalesDict_it.set("7major_neap,2", "Toni in testa (2º modo)");
scalesDict_it.set("7major_neap,4,diff:7major_nat;4", "Lidio minore (4º modo)");
scalesDict_it.set("7major_neap,5,diff:7major_nat;7", "Arabo / Locrio maggiore (5º modo)");
scalesDict_it.set("7minor_neap,1,diff:7major_nat;6", "Napolitano minore");
scalesDict_it.set("7minor_neap,2,diff:7major_nat;4", "Lidio #6 (2º modo)");
scalesDict_it.set("7minor_neap,4", "Zingaro ungherese (4º modo)");
scalesDict_it.set("7persian,1,diff:7major_2harm;1", "Persiana");
scalesDict_it.set("7persian,4", "Todi theta (4º modo)");
scalesDict_it.set("7major_hung,1", "Maggiore ungherese");
scalesDict_it.set("7verdi_enigm,1", "Enigmatica di Verdi");
scalesDict_it.set("8bebop_dom,1,diff:7major_nat;1", "Bebop dominante");
scalesDict_it.set("8bebop_dom,2,diff:7major_nat;6", "Minore naturale + Dorico (2º modo)");
scalesDict_it.set("8bebop_dom,5,diff:7major_nat;2", "Bebop dorico / Bebop minore (5º modo)");
scalesDict_it.set("8bebop_maj,1,diff:7major_nat;1", "Bebop maggiore");
scalesDict_it.set("8bebop_maj,2,diff:7major_nat;6", "Dorico + Blue note (2º modo)");
scalesDict_it.set("8bebop_maj,7,diff:7minor_harm;1", "Bebop minore armonico (7º modo)");
scalesDict_it.set("8bebop_min_melo,1,diff:7minor_melo;1", "Bebop minore melodico");
scalesDict_it.set("8spanish,1", "Spagnola");
scalesDict_it.set("8dim,1", "Diminuita");
scalesDict_it.set("8dim,2", "Dominante diminuita / Dom-dim (2º modo)");
scalesDict_it.set("6blues,1,diff:5major_penta;5", "Blues / Penta. minore + Blue note");
scalesDict_it.set("6strange,1", "Tonos / Strana / Debussy");
scalesDict_it.set("6aug,1", "Aumentata / Irlandese / Scozzese");
scalesDict_it.set("6aug,2", "6 toni simmetrici (2º modo)");
scalesDict_it.set("6prom,1", "Prométhée / Mistica");
scalesDict_it.set("6prom,4", "Mistica tritono (4º modo)");
scalesDict_it.set("6major_hexa,1", "Esatonica maggiore");
scalesDict_it.set("6prom_nap,1", "Prométhée napoletano");
scalesDict_it.set("6tritone,1", "Tritono / Petrouchka");
scalesDict_it.set("6tritone_semi,1", "2 semitoni tritono");
scalesDict_it.set("6istrian,1", "Istriana");
scalesDict_it.set("5major_penta,1", "Pentatonica maggiore / Mongolo");
scalesDict_it.set("5major_penta,5", "Pentatonica minore (5º modo)");
scalesDict_it.set("5major_penta,2", "Egiziana / Sospesa (2º modo)");
scalesDict_it.set("5major_penta,3", "Blues minore / Man gong (3º modo)");
scalesDict_it.set("5major_penta,4", "Blues maggiore / Yo / Ritsusen (4º modo)");
scalesDict_it.set("5jap_in,1", "In / Miyako-Bushi");
scalesDict_it.set("5jap_in,2", "Cinese / Pentatonica lidia (2º modo)");
scalesDict_it.set("5jap_in,3", "Hirajoshi / Tezeta (3º modo)");
scalesDict_it.set("5jap_in,4", "Iwato (4º modo)");
scalesDict_it.set("5jap_insen,1", "Insen");
scalesDict_it.set("5jap_insen,4,diff:5major_penta;5", "Pentatonica minore ♭5 (4º modo)");
scalesDict_it.set("5jap_insen,5", "Kumoi (5º modo)");
scalesDict_it.set("5javanese,1", "Giavanese / Ryu Kyu");
scalesDict_it.set("5javanese,2", "Balinesa (2º modo)");
scalesDict_it.set("5javanese,5", "Iwato bis (5º modo)");
scalesDict_it.set("5pelog_barang,2", "Pentatonica misolidia / Indù (2º modo)");
scalesDict_it.set("5dom_penta,1,diff:5major_penta;1", "Pentatonica dominante");
scalesDict_it.set("5dom_penta,4,diff:5major_penta;5", "Pentatonica dórica (4º modo)");
scalesDict_it.set("5bartok_penta,1,diff:5major_penta;5", "Pentatonica Bartok");
scalesDict_it.set("5bartok_penta,4,diff:5major_penta;5", "Pentatonica Minore Melodica (4º modo)");
scalesDict_it.set("5min_harm_penta,1,diff:5major_penta;5", "Pentatonica minore armonica");
scalesDict_it.set("5min_harm_penta,4", "Pentatonica misolidia ♭6 (4º modo)");
scalesDict_it.set("5majorb6_penta,1,diff:5major_penta;1", "Pentatonica majeure ♭6");
scalesDict_it.set("5phryg6_penta,1,diff:5major_penta;1", "Pentatonica frigia ♮6");
scalesDict_it.set("5whole_tone_penta,1", "Pentatonica 6 toni");
////////////////////////////////// PORTUGUESE //////////////////////////////////
const scalesDict_pt = new Map();
scalesDict_pt.set("12tet,1", "Cromática");
scalesDict_pt.set("7major_nat,1", "Maior natural / Jônio");
scalesDict_pt.set("7major_nat,6,diff:7major_nat;1", "Menor natural / Eólio (6º modo)");
scalesDict_pt.set("7major_nat,2,diff:7major_nat;6", "Dorico (2º modo)");
scalesDict_pt.set("7major_nat,3,diff:7major_nat;6", "Frígio (3º modo)");
scalesDict_pt.set("7major_nat,4,diff:7major_nat;1", "Lídio (4º modo)");
scalesDict_pt.set("7major_nat,5,diff:7major_nat;1", "Mixolídio (5º modo)");
scalesDict_pt.set("7major_nat,7,diff:7major_nat;6", "Lócrio (7º modo)");
scalesDict_pt.set("7minor_harm,1,diff:7major_nat;6", "Menor harmônica");
scalesDict_pt.set("7minor_harm,2,diff:7major_nat;7", "Lócrio ♮6 (2º modo)");
scalesDict_pt.set("7minor_harm,3,diff:7major_nat;1", "Jônio aumentado / Jônio #5 (3º modo)");
scalesDict_pt.set("7minor_harm,4,diff:7major_nat;2", "Menor romeno / Dórico ucraniano (4º modo)");
scalesDict_pt.set("7minor_harm,5,diff:7major_nat;3", "Frígio dominante / Frígio maior (5º modo)");
scalesDict_pt.set("7minor_harm,6,diff:7major_nat;4", "Lídio #2 (6º modo)");
scalesDict_pt.set("7minor_harm,7,diff:7major_nat;7", "Ultra Lócrio / Alterada ♭♭7 (7º modo)");
scalesDict_pt.set("7minor_melo,1,diff:7major_nat;6", "Menor melódica");
scalesDict_pt.set("7minor_melo,2,diff:7major_nat;6", "Dorico ♭2 / Frígio ♮6 (2º modo)");
scalesDict_pt.set("7minor_melo,3,diff:7major_nat;4", "Lídio aumentado / Lídio #5 (3º modo)");
scalesDict_pt.set("7minor_melo,4,diff:7major_nat;4", "Bartok / Lídio dominante (4º modo)");
scalesDict_pt.set("7minor_melo,5,diff:7major_nat;5", "Hindu / Mixolídio ♭6 (5º modo)");
scalesDict_pt.set("7minor_melo,6,diff:7major_nat;7", "Semidiminuto / Lócrio ♮2 (6º modo)");
scalesDict_pt.set("7minor_melo,7,diff:7major_nat;7", "Super Lócrio / Alterada (7º modo)");
scalesDict_pt.set("7major_2harm,1,diff:7major_nat;1", "Duplo maior harmônico / Bizantino / Cigano");
scalesDict_pt.set("7major_2harm,2,diff:7major_nat;4", "Lídio #2 #6 (2º modo)");
scalesDict_pt.set("7major_2harm,3,diff:7major_nat;3", "Ultra frígio (3º modo)");
scalesDict_pt.set("7major_2harm,4,diff:7major_nat;6", "Menor húngaro (4º modo)");
scalesDict_pt.set("7major_2harm,5", "Oriental / Asiático (5º modo)");
scalesDict_pt.set("7major_2harm,6,diff:7major_nat;1", "Ionico aumentado #2 (6º modo)");
scalesDict_pt.set("7major_2harm,7,diff:7major_nat;7", "Lócrio ♭♭3 ♭♭7 (7º modo)");
scalesDict_pt.set("7major_harm,1,diff:7major_nat;1", "Maior harmônico / Jônio ♭6");
scalesDict_pt.set("7major_harm,2,diff:7major_nat;2", "Nahawand Murassa' / Dórico ♭5 (2º modo)");
scalesDict_pt.set("7major_harm,3,diff:7major_nat;3", "Frígio ♭4 (3º modo)");
scalesDict_pt.set("7major_harm,4,diff:7major_nat;4", "Lídio ♭3 / Menor melódica #4 (4º modo)");
scalesDict_pt.set("7major_harm,5,diff:7major_nat;5", "Zanjaran / Mixolídio ♭2 (5º modo)");
scalesDict_pt.set("7major_harm,6,diff:7major_nat;4", "Lídio aumentado #2 (6º modo)");
scalesDict_pt.set("7major_harm,7,diff:7major_nat;7", "Lócrio ♭♭7 (7º modo)");
scalesDict_pt.set("7major_neap,1,diff:7minor_melo;1", "Napolitano maior");
scalesDict_pt.set("7major_neap,2", "Tons no topo (2º modo)");
scalesDict_pt.set("7major_neap,4,diff:7major_nat;4", "Lídio menor (4º modo)");
scalesDict_pt.set("7major_neap,5,diff:7major_nat;7", "Árabe / Lócrio maior (5º modo)");
scalesDict_pt.set("7minor_neap,1,diff:7major_nat;6", "Napolitano menor");
scalesDict_pt.set("7minor_neap,2,diff:7major_nat;4", "Lídio #6 (2º modo)");
scalesDict_pt.set("7minor_neap,4", "Cigano húngaro (4º modo)");
scalesDict_pt.set("7persian,1,diff:7major_2harm;1", "Persa");
scalesDict_pt.set("7persian,4", "Todi theta (4º modo)");
scalesDict_pt.set("7major_hung,1", "Maior húngaro");
scalesDict_pt.set("7verdi_enigm,1", "Enigmática de Verdi");
scalesDict_pt.set("8bebop_dom,1,diff:7major_nat;1", "Bebop dominante");
scalesDict_pt.set("8bebop_dom,2,diff:7major_nat;6", "Menor natural + Dórico (2º modo)");
scalesDict_pt.set("8bebop_dom,5,diff:7major_nat;2", "Bebop dórico / Bebop menor (5º modo)");
scalesDict_pt.set("8bebop_maj,1,diff:7major_nat;1", "Bebop majeur");
scalesDict_pt.set("8bebop_maj,2,diff:7major_nat;6", "Dorico + Blue note (2º modo)");
scalesDict_pt.set("8bebop_maj,7,diff:7minor_harm;1", "Bebop menor harmônico (7º modo)");
scalesDict_pt.set("8bebop_min_melo,1,diff:7minor_melo;1", "Bebop minore melódico");
scalesDict_pt.set("8spanish,1", "Espanhola");
scalesDict_pt.set("8dim,1", "Diminuta");
scalesDict_pt.set("8dim,2", "Dominante diminuta / Dom-dim (2º modo)");
scalesDict_pt.set("6blues,1,diff:5major_penta;5", "Blues / Penta. minore + Blue note");
scalesDict_pt.set("6strange,1", "Tonos / Estranha / Debussy");
scalesDict_pt.set("6aug,1", "Aumentada / Irlandesa / Escocesa");
scalesDict_pt.set("6aug,2", "6 tons simétricos (2º modo)");
scalesDict_pt.set("6prom,1", "Prometeu / Mística");
scalesDict_pt.set("6prom,4", "Mística trítono (4º modo)");
scalesDict_pt.set("6major_hexa,1", "Hexatônica maior");
scalesDict_pt.set("6prom_nap,1", "Prometeu napoletano");
scalesDict_pt.set("6tritone,1", "Trítono / Petrouchka");
scalesDict_pt.set("6tritone_semi,1", "2 semitons trítono");
scalesDict_pt.set("6istrian,1", "Istriano");
scalesDict_pt.set("5major_penta,1", "Pentatônica maior / Mongol");
scalesDict_pt.set("5major_penta,5", "Pentatônica menor (5º modo)");
scalesDict_pt.set("5major_penta,2", "Egípcio / Suspensa (2º modo)");
scalesDict_pt.set("5major_penta,3", "Blues mineur / Man gong (3º modo)");
scalesDict_pt.set("5major_penta,4", "Blues majeur / Yo / Ritsusen (4º modo)");
scalesDict_pt.set("5jap_in,1", "In / Miyako-Bushi");
scalesDict_pt.set("5jap_in,2", "Chinês / Pentatônica lidia (2º modo)");
scalesDict_pt.set("5jap_in,3", "Hirajoshi / Tezeta (3º modo)");
scalesDict_pt.set("5jap_in,4", "Iwato (4º modo)");
scalesDict_pt.set("5jap_insen,1", "Insen");
scalesDict_pt.set("5jap_insen,4,diff:5major_penta;5", "Pentatônica menor ♭5 (4º modo)");
scalesDict_pt.set("5jap_insen,5", "Kumoi (5º modo)");
scalesDict_pt.set("5javanese,1", "Javanesa / Ryu Kyu");
scalesDict_pt.set("5javanese,2", "Balinesa (2º modo)");
scalesDict_pt.set("5javanese,5", "Iwato bis (5º modo)");
scalesDict_pt.set("5pelog_barang,2", "Pentatônica mixolídia / Hindu (2º modo)");
scalesDict_pt.set("5dom_penta,1,diff:5major_penta;1", "Pentatônica dominante");
scalesDict_pt.set("5dom_penta,4,diff:5major_penta;5", "Pentatônica dórica (4º modo)");
scalesDict_pt.set("5bartok_penta,1,diff:5major_penta;5", "Pentatônica Bartok");
scalesDict_pt.set("5bartok_penta,4,diff:5major_penta;5", "Pentatônica Menor Melódica (4º modo)");
scalesDict_pt.set("5min_harm_penta,1,diff:5major_penta;5", "Pentatônica menor harmônica");
scalesDict_pt.set("5min_harm_penta,4", "Pentatônica mixolídia ♭6 (4º modo)");
scalesDict_pt.set("5majorb6_penta,1,diff:5major_penta;1", "Pentatônica majeure ♭6");
scalesDict_pt.set("5phryg6_penta,1,diff:5major_penta;1", "Pentatônica frígia ♮6");
scalesDict_pt.set("5whole_tone_penta,1", "Pentatônica 6 tons");
////////////////////////////////// GERMAN //////////////////////////////////
const scalesDict_de = new Map();
scalesDict_de.set("12tet,1", "Chromatisch");
scalesDict_de.set("7major_nat,1", "Dur / Ionisch");
scalesDict_de.set("7major_nat,6,diff:7major_nat;1", "Natürlich Moll / Äolisch (6. Modus)");
scalesDict_de.set("7major_nat,2,diff:7major_nat;6", "Dorisch (2. Modus)");
scalesDict_de.set("7major_nat,3,diff:7major_nat;6", "Phrygisch (3. Modus)");
scalesDict_de.set("7major_nat,4,diff:7major_nat;1", "Lydisch (4. Modus)");
scalesDict_de.set("7major_nat,5,diff:7major_nat;1", "Mixolydisch (5. Modus)");
scalesDict_de.set("7major_nat,7,diff:7major_nat;6", "Lokrisch (7. Modus)");
scalesDict_de.set("7minor_harm,1,diff:7major_nat;6", "Harmonisch Moll");
scalesDict_de.set("7minor_harm,2,diff:7major_nat;7", "Lokrisch ♮6 (2. Modus)");
scalesDict_de.set("7minor_harm,3,diff:7major_nat;1", "Erhöht Ionisch / Ionisch #5 (3. Modus)");
scalesDict_de.set("7minor_harm,4,diff:7major_nat;2", "Rumänisch Moll / Ukrainisch Dorisch (4. Modus)");
scalesDict_de.set("7minor_harm,5,diff:7major_nat;3", "Phrygisch dominant / Phrygisch Dur (5. Modus)");
scalesDict_de.set("7minor_harm,6,diff:7major_nat;4", "Lydisch #2 (6. Modus)");
scalesDict_de.set("7minor_harm,7,diff:7major_nat;7", "Ultra Lokrisch / Alteriert ♭♭7 (7. Modus)");
scalesDict_de.set("7minor_melo,1,diff:7major_nat;6", "Melodisch Moll");
scalesDict_de.set("7minor_melo,2,diff:7major_nat;6", "Dorisch ♭2 / Phrygisch ♮6 (2. Modus)");
scalesDict_de.set("7minor_melo,3,diff:7major_nat;4", "Erhöht Lydisch / Lydisch #5 (3. Modus)");
scalesDict_de.set("7minor_melo,4,diff:7major_nat;4", "Bartok / Lydisch Dominant (4. Modus)");
scalesDict_de.set("7minor_melo,5,diff:7major_nat;5", "Hindu / Mixolydisch ♭6 (5. Modus)");
scalesDict_de.set("7minor_melo,6,diff:7major_nat;7", "Halbvermindert / Lokrisch ♮2 (6. Modus)");
scalesDict_de.set("7minor_melo,7,diff:7major_nat;7", "Super Lokrisch / Alteriert (7. Modus)");
scalesDict_de.set("7major_2harm,1,diff:7major_nat;1", "Doppel harmonisch Dur / Byzantinisch / Zigeuner");
scalesDict_de.set("7major_2harm,2,diff:7major_nat;4", "Lydisch #2 #6 (2. Modus)");
scalesDict_de.set("7major_2harm,3,diff:7major_nat;3", "Ultra phrygisch (3. Modus)");
scalesDict_de.set("7major_2harm,4,diff:7major_nat;6", "Ungarisch Moll (4. Modus)");
scalesDict_de.set("7major_2harm,5", "Orientalisch / Asiatisch (5. Modus)");
scalesDict_de.set("7major_2harm,6,diff:7major_nat;1", "Erhöht Ionisch #2 (6. Modus)");
scalesDict_de.set("7major_2harm,7,diff:7major_nat;7", "Lokrisch ♭♭3 ♭♭7 (7. Modus)");
scalesDict_de.set("7major_harm,1,diff:7major_nat;1", "Harmonisch Dur / Ionisch ♭6");
scalesDict_de.set("7major_harm,2,diff:7major_nat;2", "Nahawand Murassa' / Dorisch ♭5 (2. Modus)");
scalesDict_de.set("7major_harm,3,diff:7major_nat;3", "Phrygisch ♭4 (3. Modus)");
scalesDict_de.set("7major_harm,4,diff:7major_nat;4", "Lydisch ♭3 / Minere mélodica #4 (4. Modus)");
scalesDict_de.set("7major_harm,5,diff:7major_nat;5", "Zanjaran / Mixolydisch ♭2 (5. Modus)");
scalesDict_de.set("7major_harm,6,diff:7major_nat;4", "Erhöht Lydisch #2 (6. Modus)");
scalesDict_de.set("7major_harm,7,diff:7major_nat;7", "Lokrisch ♭♭7 (7. Modus)");
scalesDict_de.set("7major_neap,1,diff:7minor_melo;1", "Neapolitanisch Dur");
scalesDict_de.set("7major_neap,2", "Töne am Anfang (2. Modus)");
scalesDict_de.set("7major_neap,4,diff:7major_nat;4", "Lydisch Moll (4. Modus)");
scalesDict_de.set("7major_neap,5,diff:7major_nat;7", "Arabisch / Lokrisch Dur (5. Modus)");
scalesDict_de.set("7minor_neap,1,diff:7major_nat;6", "Neapolitanisch Moll");
scalesDict_de.set("7minor_neap,2,diff:7major_nat;4", "Lydisch #6 (2. Modus)");
scalesDict_de.set("7minor_neap,4", "Ungarisch Zigeuner (4. Modus)");
scalesDict_de.set("7persian,1,diff:7major_2harm;1", "Persisch");
scalesDict_de.set("7persian,4", "Todi theta (4. Modus)");
scalesDict_de.set("7major_hung,1", "Ungarisch Dur");
scalesDict_de.set("7verdi_enigm,1", "Verdis Enigmatica");
scalesDict_de.set("8bebop_dom,1,diff:7major_nat;1", "Bebop dominante");
scalesDict_de.set("8bebop_dom,2,diff:7major_nat;6", "Natürlich Moll + Dorisch (2. Modus)");
scalesDict_de.set("8bebop_dom,5,diff:7major_nat;2", "Bebop dorisch / Bebop Moll (5. Modus)");
scalesDict_de.set("8bebop_maj,1,diff:7major_nat;1", "Bebop Dur");
scalesDict_de.set("8bebop_maj,2,diff:7major_nat;6", "Dorisch + Blue note (2. Modus)");
scalesDict_de.set("8bebop_maj,7,diff:7minor_harm;1", "Bebop harmonisch Moll (7. Modus)");
scalesDict_de.set("8bebop_min_melo,1,diff:7minor_melo;1", "Bebop melodisch Moll");
scalesDict_de.set("8spanish,1", "Spanisch");
scalesDict_de.set("8dim,1", "Vermindert");
scalesDict_de.set("8dim,2", "Dominant vermindert / Dom-dim (2. Modus)");
scalesDict_de.set("6blues,1,diff:5major_penta;5", "Blues / Penta. minore + Blue note");
scalesDict_de.set("6strange,1", "Tonos / Seltsam / Debussy");
scalesDict_de.set("6aug,1", "Erhöht / Irisch / Schottisch");
scalesDict_de.set("6aug,2", "6 symmetrische Töne (2. Modus)");
scalesDict_de.set("6prom,1", "Prometheus / Mystisch");
scalesDict_de.set("6prom,4", "Mystisch Tritonus (4. Modus)");
scalesDict_de.set("6major_hexa,1", "Hexatonisch Dur");
scalesDict_de.set("6prom_nap,1", "Prometheus neapolitanisch");
scalesDict_de.set("6tritone,1", "Tritonus / Petrouchka");
scalesDict_de.set("6tritone_semi,1", "2 Halbton Tritonus");
scalesDict_de.set("6istrian,1", "Istrisch");
scalesDict_de.set("5major_penta,1", "Pentatonisch Dur / Mongolisch");
scalesDict_de.set("5major_penta,5", "Pentatonisch Moll (5. Modus)");
scalesDict_de.set("5major_penta,2", "Ägyptisch / Suspended (2. Modus)");
scalesDict_de.set("5major_penta,3", "Blues Moll / Man gong (3. Modus)");
scalesDict_de.set("5major_penta,4", "Blues Dur / Yo / Ritsusen (4. Modus)");
scalesDict_de.set("5jap_in,1", "In / Miyako-Bushi");
scalesDict_de.set("5jap_in,2", "Chinesisch / Pentatonisch lydisch (2. Modus)");
scalesDict_de.set("5jap_in,3", "Hirajoshi / Tezeta (3. Modus)");
scalesDict_de.set("5jap_in,4", "Iwato (4. Modus)");
scalesDict_de.set("5jap_insen,1", "Insen");
scalesDict_de.set("5jap_insen,4,diff:5major_penta;5", "Pentatonisch moll ♭5 (4. Modus)");
scalesDict_de.set("5jap_insen,5", "Kumoi (5. Modus)");
scalesDict_de.set("5javanese,1", "Javanisch / Ryu Kyu");
scalesDict_de.set("5javanese,2", "Balinesisch (2. Modus)");
scalesDict_de.set("5javanese,5", "Iwato bis (5. Modus)");
scalesDict_de.set("5pelog_barang,2", "Pentatonisch Mixolydisch / Hindu (2. Modus)");
scalesDict_de.set("5dom_penta,1,diff:5major_penta;1", "Pentatonisch dominant");
scalesDict_de.set("5dom_penta,4,diff:5major_penta;5", "Pentatonisch dorisch (4. Modus)");
scalesDict_de.set("5bartok_penta,1,diff:5major_penta;5", "Pentatonisch Bartok");
scalesDict_de.set("5bartok_penta,4,diff:5major_penta;5", "Pentatonisch melodisch moll (4. Modus)");
scalesDict_de.set("5min_harm_penta,1,diff:5major_penta;5", "Pentatonisch harmonisch moll");
scalesDict_de.set("5min_harm_penta,4", "Pentatonisch Mixolydisch ♭6 (4. Modus)");
scalesDict_de.set("5majorb6_penta,1,diff:5major_penta;1", "Pentatonisch dur ♭6");
scalesDict_de.set("5phryg6_penta,1,diff:5major_penta;1", "Pentatonisch phrygisch ♮6");
scalesDict_de.set("5whole_tone_penta,1", "Pentatonisch 6 Töne");
////////////////////////////////// VIETNAMESE //////////////////////////////////
const scalesDict_vn = new Map();
scalesDict_vn.set("12tet,1", "Sắc thái");
scalesDict_vn.set("7major_nat,1", "Trưởng tự nhiên / Ionian");
scalesDict_vn.set("7major_nat,6,diff:7major_nat;1", "Thứ tự nhiên / Aeolian (chế độ 6)");
scalesDict_vn.set("7major_nat,2,diff:7major_nat;6", "Dorian (chế độ 2)");
scalesDict_vn.set("7major_nat,3,diff:7major_nat;6", "Phrygian (chế độ 3)");
scalesDict_vn.set("7major_nat,4,diff:7major_nat;1", "Lydian (chế độ 4)");
scalesDict_vn.set("7major_nat,5,diff:7major_nat;1", "Mixolydian (chế độ 5)");
scalesDict_vn.set("7major_nat,7,diff:7major_nat;6", "Locrian (chế độ 7)");
scalesDict_vn.set("7minor_harm,1,diff:7major_nat;6", "Thứ hòa âm");
scalesDict_vn.set("7minor_harm,2,diff:7major_nat;7", "Locrian ♮6 (chế độ 2)");
scalesDict_vn.set("7minor_harm,3,diff:7major_nat;1", "Ionian tăng / Ionian #5 (chế độ 3)");
scalesDict_vn.set("7minor_harm,4,diff:7major_nat;2", "Thứ Rumani / Dorian Ukraina (chế độ 4)");
scalesDict_vn.set("7minor_harm,5,diff:7major_nat;3", "Phrygian dominant / Phrygian trưởng (chế độ 5)");
scalesDict_vn.set("7minor_harm,6,diff:7major_nat;4", "Lydian #2 (chế độ 6)");
scalesDict_vn.set("7minor_harm,7,diff:7major_nat;7", "Ultra Locrian / Altered ♭♭7 (chế độ 7)");
scalesDict_vn.set("7minor_melo,1,diff:7major_nat;6", "Thứ giai điệu");
scalesDict_vn.set("7minor_melo,2,diff:7major_nat;6", "Dorian ♭2 / Phrygian ♮6 (chế độ 2)");
scalesDict_vn.set("7minor_melo,3,diff:7major_nat;4", "Lydian tăng / Lydian #5 (chế độ 3)");
scalesDict_vn.set("7minor_melo,4,diff:7major_nat;4", "Bartok / Lydian dominant (chế độ 4)");
scalesDict_vn.set("7minor_melo,5,diff:7major_nat;5", "Hindu / Mixolydian ♭6 (chế độ 5)");
scalesDict_vn.set("7minor_melo,6,diff:7major_nat;7", "Bán giảm / Locrian ♮2 (chế độ 6)");
scalesDict_vn.set("7minor_melo,7,diff:7major_nat;7", "Super Locrian / Altered (chế độ 7)");
scalesDict_vn.set("7major_2harm,1,diff:7major_nat;1", "Trưởng kép hòa âm / Byzantine / Gypsy");
scalesDict_vn.set("7major_2harm,2,diff:7major_nat;4", "Lydian #2 #6 (chế độ 2)");
scalesDict_vn.set("7major_2harm,3,diff:7major_nat;3", "Ultra phrygian (chế độ 3)");
scalesDict_vn.set("7major_2harm,4,diff:7major_nat;6", "Thứ Hungary (chế độ 4)");
scalesDict_vn.set("7major_2harm,5", "Phương Đông / Châu Á (chế độ 5)");
scalesDict_vn.set("7major_2harm,6,diff:7major_nat;1", "Ionian tăng #2 (chế độ 6)");
scalesDict_vn.set("7major_2harm,7,diff:7major_nat;7", "Locrian ♭♭3 ♭♭7 (chế độ 7)");
scalesDict_vn.set("7major_harm,1,diff:7major_nat;1", "Trưởng hòa âm / Ionian ♭6");
scalesDict_vn.set("7major_harm,2,diff:7major_nat;2", "Nahawand Murassa' / Dorian ♭5 (chế độ 2)");
scalesDict_vn.set("7major_harm,3,diff:7major_nat;3", "Phrygian ♭4 (chế độ 3)");
scalesDict_vn.set("7major_harm,4,diff:7major_nat;4", "Lydian ♭3 / Thứ giai điệu #4 (chế độ 4)");
scalesDict_vn.set("7major_harm,5,diff:7major_nat;5", "Zanjaran / Mixolydian ♭2 (chế độ 5)");
scalesDict_vn.set("7major_harm,6,diff:7major_nat;4", "Lydian tăng #2 (chế độ 6)");
scalesDict_vn.set("7major_harm,7,diff:7major_nat;7", "Locrian ♭♭7 (chế độ 7)");
scalesDict_vn.set("7major_neap,1,diff:7minor_melo;1", "Trưởng Neapolitan");
scalesDict_vn.set("7major_neap,2", "Nốt đầu (chế độ 2)");
scalesDict_vn.set("7major_neap,4,diff:7major_nat;4", "Lydian thứ (chế độ 4)");
scalesDict_vn.set("7major_neap,5,diff:7major_nat;7", "Ả Rập / Locrian trưởng (chế độ 5)");
scalesDict_vn.set("7minor_neap,1,diff:7major_nat;6", "Thứ Neapolitan");
scalesDict_vn.set("7minor_neap,2,diff:7major_nat;4", "Lydian #6 (chế độ 2)");
scalesDict_vn.set("7minor_neap,4", "Gypsy Hungary (chế độ 4)");
scalesDict_vn.set("7persian,1,diff:7major_2harm;1", "Ba Tư");
scalesDict_vn.set("7persian,4", "Todi theta (chế độ 4)");
scalesDict_vn.set("7major_hung,1", "Trưởng Hungary");
scalesDict_vn.set("7verdi_enigm,1", "Verdi bí ẩn");
scalesDict_vn.set("8bebop_dom,1,diff:7major_nat;1", "Bebop dominant");
scalesDict_vn.set("8bebop_dom,2,diff:7major_nat;6", "Thứ tự nhiên + Dorian (chế độ 2)");
scalesDict_vn.set("8bebop_dom,5,diff:7major_nat;2", "Bebop Dorian / Bebop thứ (chế độ 5)");
scalesDict_vn.set("8bebop_maj,1,diff:7major_nat;1", "Bebop trưởng");
scalesDict_vn.set("8bebop_maj,2,diff:7major_nat;6", "Dorian + Blue note (chế độ 2)");
scalesDict_vn.set("8bebop_maj,7,diff:7minor_harm;1", "Bebop thứ hòa âm (chế độ 7)");
scalesDict_vn.set("8bebop_min_melo,1,diff:7minor_melo;1", "Bebop thứ giai điệu");
scalesDict_vn.set("8spanish,1", "Tây Ban Nha");
scalesDict_vn.set("8dim,1", "Giảm");
scalesDict_vn.set("8dim,2", "Dominant giảm / Dom-dim (chế độ 2)");
scalesDict_vn.set("6blues,1,diff:5major_penta;5", "Blues / Penta. thứ + Blue note");
scalesDict_vn.set("6strange,1", "Âm sắc / Lạ / Debussy");
scalesDict_vn.set("6aug,1", "Tăng / Ireland / Scotland");
scalesDict_vn.set("6aug,2", "6 âm đối xứng (chế độ 2)");
scalesDict_vn.set("6prom,1", "Prometheus / Huyền bí");
scalesDict_vn.set("6prom,4", "Huyền bí Tritone (chế độ 4)");
scalesDict_vn.set("6major_hexa,1", "Hexatonic trưởng");
scalesDict_vn.set("6prom_nap,1", "Prometheus Neapolitan");
scalesDict_vn.set("6tritone,1", "Tritone / Petrouchka");
scalesDict_vn.set("6tritone_semi,1", "2 bán cung Tritone");
scalesDict_vn.set("6istrian,1", "Istrian");
scalesDict_vn.set("5major_penta,1", "Ngũ cung trưởng / Mông Cổ");
scalesDict_vn.set("5major_penta,5", "Ngũ cung thứ (chế độ 5)");
scalesDict_vn.set("5major_penta,2", "Ai Cập / Treo (chế độ 2)");
scalesDict_vn.set("5major_penta,3", "Blues thứ / Man gong (chế độ 3)");
scalesDict_vn.set("5major_penta,4", "Blues trưởng / Yo / Ritsusen (chế độ 4)");
scalesDict_vn.set("5jap_in,1", "In / Miyako-Bushi");
scalesDict_vn.set("5jap_in,2", "Trung Quốc / Ngũ cung lydian (chế độ 2)");
scalesDict_vn.set("5jap_in,3", "Hirajoshi / Tezeta (chế độ 3)");
scalesDict_vn.set("5jap_in,4", "Iwato (chế độ 4)");
scalesDict_vn.set("5jap_insen,1", "Insen");
scalesDict_vn.set("5jap_insen,4,diff:5major_penta;5", "Ngũ cung thứ ♭5 (chế độ 4)");
scalesDict_vn.set("5jap_insen,5", "Kumoi (chế độ 5)");
scalesDict_vn.set("5javanese,1", "Java / Ryu Kyu");
scalesDict_vn.set("5javanese,2", "Bali (chế độ 2)");
scalesDict_vn.set("5javanese,5", "Iwato bis (chế độ 5)");
scalesDict_vn.set("5pelog_barang,2", "Ngũ cung Mixolydian / Hindu (chế độ 2)");
scalesDict_vn.set("5dom_penta,1,diff:5major_penta;1", "Ngũ cung dominant");
scalesDict_vn.set("5dom_penta,4,diff:5major_penta;5", "Ngũ cung Dorian (chế độ 4)");
scalesDict_vn.set("5bartok_penta,1,diff:5major_penta;5", "Ngũ cung Bartok");
scalesDict_vn.set("5bartok_penta,4,diff:5major_penta;5", "Ngũ cung Thứ giai điệu (chế độ 4)");
scalesDict_vn.set("5min_harm_penta,1,diff:5major_penta;5", "Ngũ cung thứ hòa âm");
scalesDict_vn.set("5min_harm_penta,4", "Ngũ cung Mixolydian ♭6 (chế độ 4)");
scalesDict_vn.set("5majorb6_penta,1,diff:5major_penta;1", "Ngũ cung trưởng ♭6");
scalesDict_vn.set("5phryg6_penta,1,diff:5major_penta;1", "Ngũ cung Phrygian ♮6");
scalesDict_vn.set("5whole_tone_penta,1", "Ngũ cung 6 âm đối xứng");
// global dictionary
const scalesDicts = new Map();
scalesDicts.set("int", scalesDict_int);
scalesDicts.set("de", scalesDict_de);
scalesDicts.set("es", scalesDict_es);
scalesDicts.set("fr", scalesDict_fr);
scalesDicts.set("it", scalesDict_it);
scalesDicts.set("pt", scalesDict_pt);
scalesDicts.set("vn", scalesDict_vn);
/////////////////////////////////// FUNCTIONS /////////////////////////////////
const scalesToHighlight = ["12tet,1",
    "7major_nat,1", "7major_nat,6", "7minor_harm,1", "7minor_melo,1",
    "7major_2harm,1", "7major_harm,1", "7major_neap,1", "7minor_neap,1", "7persian,1",
    "7bayati,1", "7hardino,1", "7hijaz,1", "7rast,1", "7mahur", "7mustaar", "7saba", "7sikah_baladi,1",
    "8bebop_dom,1", "8bebop_maj,1", "8dim,1", "8harmonic_approx",
    "6blues,1", "6strange,1", "6aug,1", "6prom,1",
    "5major_penta,1", "5major_penta,5", "5jap_in,1", "5jap_insen,1", "5javanese,1", "5pelog_barang,1", "5dom_penta,1", "5bartok_penta,1", "5min_harm_penta,1",
    "24tet,1"
];
function hightlightScale(id) {
    if (scalesToHighlight.indexOf(id) != -1)
        return true;
    let found = false;
    scalesToHighlight.forEach(function (idScale, index) {
        if (id.startsWith(idScale))
            found = true;
    });
    return found;
}
//# sourceMappingURL=scales.js.map